package dev.fishies.sailfish.gui.util

operator fun <T> Array<T>.component1() = this[0]
operator fun <T> Array<T>.component2() = this[1]
operator fun <T> Array<T>.component3() = this[2]
operator fun <T> Array<T>.component4() = this[3]
operator fun <T> Array<T>.component5() = this[4]
operator fun <T> Array<T>.component6() = this[5]
operator fun <T> Array<T>.component7() = this[6]
operator fun <T> Array<T>.component8() = this[7]
operator fun <T> Array<T>.component9() = this[8]
operator fun <T> Array<T>.component10() = this[9]
operator fun <T> Array<T>.component11() = this[10]
operator fun <T> Array<T>.component12() = this[11]
operator fun <T> Array<T>.component13() = this[12]
operator fun <T> Array<T>.component14() = this[13]
operator fun <T> Array<T>.component15() = this[14]
operator fun <T> Array<T>.component16() = this[15]
operator fun <T> Array<T>.component17() = this[16]
operator fun <T> Array<T>.component18() = this[17]
operator fun <T> Array<T>.component19() = this[18]
operator fun <T> Array<T>.component20() = this[19]
operator fun <T> Array<T>.component21() = this[20]
operator fun <T> Array<T>.component22() = this[21]
operator fun <T> Array<T>.component23() = this[22]
operator fun <T> Array<T>.component24() = this[23]
operator fun <T> Array<T>.component25() = this[24]
